//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasetaDeVigilancia
{
    using System;
    using System.Collections.Generic;
    
    public partial class historialacceso
    {
        public int HistorialID { get; set; }
        public int UsuarioID { get; set; }
        public int InvitadoID { get; set; }
        public Nullable<System.DateTime> fechaEntrada { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
