//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasetaDeVigilancia
{
    using System;
    using System.Collections.Generic;
    
    public partial class invitado
    {
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public System.DateTime fechaVigencia { get; set; }
        public sbyte status { get; set; }
        public int InvitadoID { get; set; }
        public int Usuario_UserID { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
